# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: publish to modrinth and curseforge

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: Upload a forge build
        uses: actions/upload-artifact@v2.2.2
        with:
          path: build/libs/**.jar
          name: forge
          retention-days: 2

  publish_forge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: forge
          path: download

      - name: remove modloader prefix from version
        run: echo "version_name=$(echo "${{ github.event.release.tag_name }}" | cut -c 7-)" >> $GITHUB_ENV

      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: pNabrMMw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 459929
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          changelog-file: CHANGELOG.md
          github-generate-changelog: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          loaders: forge
          game-versions: 1.19.3
          curseforge-dependencies: |
            cloth-config | depends
            applied-energistics-2 | depends
            architectury-api | depends
            curios | depends
          modrinth-dependencies: |
            cloth-config | depends
            ae2 | depends
            architectury-api | depends
          java: 17
          version: ${{ env.version_name }}-forge
          name: ${{ env.version_name }}-forge
          files-primary: download/!(*-@(dev|dev-shadow|sources)).jar
          files-secondary: ""